# Generated by Django 5.1.7 on 2025-03-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20250327_1450'),
    ]

    operations = [
    ]
